blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from blogsite.feeds import AllPostsRssFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('blogsite.urls')),  #Django会把这个url正则里面的内容和blogsite里面url的内容进行拼接
    url(r'',include('comments.urls')),
    url(r'^all/rss/$',AllPostsRssFeed(),name='rss'),
    url(r'^search/',include('haystack.urls')),
]

blogsite/urls.py
from django.conf.urls import url
from blogsite import views

app_name = 'blogsite'  #指定命名空间
urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'), #如果是类视图也要相应更改url
    url(r'^post/(?P<pk>[0-9]+)/$',views.detail,name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.archives,name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.category,name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
    # url(r'^search/$',views.search,name='search'),

]

comments/urls.py
from django.conf.urls import url

from . import views
app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name='post_comments'),
]

blogsite/models.py
from django.db import models
from django.contrib.auth.models import User   #Django内置的用户模块
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

class Post(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    create_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    views = models.PositiveIntegerField(default=0)  #设置浏览量
    author = models.ForeignKey(User,on_delete=models.CASCADE)

    def increase_vies(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_time']

    def get_absolute_url(self):
        return reverse('blogsite:detail',kwargs={'pk':self.pk})

comments/models.py
from django.db import models

class Comment(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField()
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blogsite.Post',on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','url','text']
#如果有数据库模型，那么使用ModelForm会更简单

blogsite/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post,Category,Tag
import markdown
from comments.forms import CommentForm
from django.views.generic import ListView
from django.db.models import Q


class IndexView(ListView):
    model = Post
    template_name = 'blogsite/index.html'
    context_object_name = 'post_list'     #使用类视图方法进行改写
    paginate_by = 2  #设置分页，每页显示的数量




# def index(request):
#     post_list = Post.objects.all()
#     return render(request, 'blogsite/index.html', context={'post_list': post_list})


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.increase_vies()   #如果有人访问，那么浏览量加一
    post.body = markdown.markdown(post.body, [
        'extra',
        'codehilite',
        'toc',
    ])
    form = CommentForm()
    comment_list = post.comment_set.all()
    context = {
        'post':post,
        'form':form,
        'comment_list':comment_list,
    }
    return render(request, 'blogsite/detail.html', context=context)


def archives(request, year, month):
    post_list = Post.objects.filter(create_time__year=year,
                                    create_time__month=month)
    return render(request, 'blogsite/index.html', context={'post_list': post_list})

def category(request,pk):
    cate = get_object_or_404(Category,pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request,'blogsite/index.html',context={'post_list':post_list})


class TagView(ListView):
    model = Post
    template_name = 'blogsite/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = '请输入关键词'
        return render(request,'blogsite/index.html')
    post_list = Post.objects.filter(Q(title__icontains=q) |Q(body__icontains=q))
    return render(request,'blogsite/index.html',{
        'error_msg':error_msg,
        'post_list':post_list,
    })

comments/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404,redirect
from .models import Comment
from .forms import CommentForm
from blogsite.models import Post

def post_comment(request,post_pk):
    post = get_object_or_404(Post,pk = post_pk)
    # form = CommentForm(request.POST)  # 构造表单
    if request.method == 'POST':
        form = CommentForm(request.POST)  #构造表单
        if form.is_valid():    #检查数据合法性
            comment = form.save(commit=False)   #这个地方一定要注意是false，因为是外键。
            comment.post = post
            comment.save()
            return redirect(post)
            # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
            # 然后重定向到 get_absolute_url 方法返回的 URL。
        else:
            comment_list = post.comment_set.all() #反向查询所有的评论
            context ={
                'post':post,
                'form':form,
                'comment_list':comment_list
            }
            return render(request,'blogsite/detail.html',context=context)
    return redirect(post)

templates/base.html
{% load staticfiles %}
{% load blogsite_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blogsite/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blogsite/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blogsite/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blogsite/css/highlights/github.css' %}">
    <!-- js -->
    <script src="{% static 'blogsite/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blogsite/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blogsite/js/pace.min.js' %}"></script>
    <script src="{% static 'blogsite/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blogsite:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blogsite:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" placeholder="搜索" name="q" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
{% block main %}

{% endblock %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                
                {% endblock %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                        {% empty %}
                        暂无文章
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li><a href="{% url 'blogsite:archives' date.year date.month %}">{{ date.year }}年{{ date.month }}月</a></li>
                            {% empty %}
                            暂无归档
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li><a href="{% url 'blogsite:category' category.pk %}">
                                {{ category.name }}
                                <span class="post-count">{{ category.num_posts }}</span>
                            </a></li>
                        {% empty %}
                            暂无分类
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blogsite:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                            {% empty %}
                            暂无标签
                        {% endfor %}




                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">彭洪</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blogsite/js/script.js' %}"></script>

</body>
</html>

templates/blogsite/detail.html
{% extends 'base.html' %}
{% block main %}
<article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                       {{ post.body |safe }}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comments' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_lable }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_label }}">评论：</label>
                               {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ comment_list |length }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                             <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                                {% empty %}
                                暂无评论
                            {% endfor %}

                        </ul>
                    </div>
                </section>
{% endblock %}
{% block toc %}
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    <ul>
                        <li>
                            <a href="#">教程特点</a>
                        </li>
                        <li>
                            <a href="#">谁适合这个教程</a>
                        </li>
                        <li>
                            <a href="#">在线预览</a>
                        </li>
                        <li>
                            <a href="#">资源列表</a>
                        </li>
                        <li>
                            <a href="#">获取帮助</a>
                        </li>
                    </ul>
                </div>
{% endblock %}

templates/blogsite/index.html
{% extends 'base.html' %}
{% block main %}
    {% if error_msg %}
<p>{{ error_msg }}</p>
    {% endif %}
     {% for post in post_list %}
               <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{ post.create_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {% if post.excerpt %}
                        <p>{{ post.excerpt }}</p>
                            {% else %}
                            <p>{{ post.body|truncatechars:20 }}</p>
                                {#  注意之间不能有空格#}
                        {% endif %}

                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                   {% empty %}
                   <div class="no-post">暂时没有发布任何文章</div>
               {% endfor %}




                {% if is_paginated %}
                 <div class="pagination-simple">
                   {% if page_obj.has_previous %}
                     <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                    {% endif %}

                    <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
                 {% if page_obj.has_next %}
                  <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                 {% endif %}
                </div>
                {% endif %}


{#                <div class="pagination">#}
{#                    <ul>#}
{#                        <li><a href="">1</a></li>#}
{#                        <li><a href="">...</a></li>#}
{#                        <li><a href="">4</a></li>#}
{#                        <li><a href="">5</a></li>#}
{#                        <li class="current"><a href="">6</a></li>#}
{#                        <li><a href="">7</a></li>#}
{#                        <li><a href="">8</a></li>#}
{#                        <li><a href="">...</a></li>#}
{#                        <li><a href="">11</a></li>#}
{#                    </ul>#}
{#                </div>#}
{% endblock %}

templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}
{% highlight result.object.title with query %}
{% highlight result.object.body with query %}

{% block main %}
    {% if query %}
        {% for result in page.object_list %}
            <article class="post post-{{ result.object.pk }}">
                <header class="entry-header">
                    <h1 class="entry-title">
                        <a href="{{ result.object.get_absolute_url }}">{% highlight result.object.title with query %}</a>
                    </h1>
                    <div class="entry-meta">
                    <span class="post-category">
                        <a href="{% url 'blog:category' result.object.category.pk %}">
                            {{ result.object.category.name }}</a></span>
                        <span class="post-date"><a href="#">
                            <time class="entry-date" datetime="{{ result.object.created_time }}">
                                {{ result.object.created_time }}</time></a></span>
                        <span class="post-author"><a href="#">{{ result.object.author }}</a></span>
                        <span class="comments-link">
                        <a href="{{ result.object.get_absolute_url }}#comment-area">
                            {{ result.object.comment_set.count }} 评论</a></span>
                        <span class="views-count"><a
                                href="{{ result.object.get_absolute_url }}">{{ result.object.views }} 阅读</a></span>
                    </div>
                </header>
                <div class="entry-content clearfix">
                    <p>{% highlight result.object.body with query %}</p>
                    <div class="read-more cl-effect-14">
                        <a href="{{ result.object.get_absolute_url }}" class="more-link">继续阅读 <span
                                class="meta-nav">→</span></a>
                    </div>
                </div>
            </article>
        {% empty %}
            <div class="no-post">没有搜索到你想要的结果！</div>
        {% endfor %}
        {% if page.has_previous or page.has_next %}
            <div>
                {% if page.has_previous %}
                    <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous
                {% if page.has_previous %}</a>{% endif %}
                |
                {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next
                &raquo;{% if page.has_next %}</a>{% endif %}
            </div>
        {% endif %}
    {% else %}
        请输入搜索关键词，例如 django
    {% endif %}
{% endblock main %}